# Generated by Django 3.0.2 on 2020-01-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lots',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
