# Generated by Django 3.0.2 on 2020-02-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0002_auto_20200127_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='lots',
            name='img',
            field=models.FileField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
