# Generated by Django 3.0.2 on 2020-02-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0003_lots_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lots',
            name='img',
        ),
    ]
