# Generated by Django 3.0.2 on 2020-01-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0005_auto_20200125_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lots',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='lots',
            old_name='modifier',
            new_name='modified_by',
        ),
    ]
