# Generated by Django 3.0.2 on 2020-01-26 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_auto_20200105_1124'),
        ('lots', '0006_auto_20200125_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lots',
            name='artist',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='artists.Artist'),
        ),
    ]
