# Generated by Django 3.0.2 on 2020-01-31 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0002_auto_20200105_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tetelek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('artist', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='artists.Artist')),
            ],
        ),
    ]
