# Generated by Django 3.0.2 on 2020-02-03 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artists', '0002_auto_20200105_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tetelek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artists.Artist')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET('1'), related_name='created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=models.SET('1'), related_name='modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
