# Generated by Django 3.0.2 on 2020-02-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tetelek', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tetelek',
            name='code',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
