# Generated by Django 3.0.2 on 2020-02-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tetelek', '0002_tetelek_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tetelek',
            name='photo',
            field=models.ImageField(default='media/images/default.jpg', upload_to='images/'),
        ),
    ]
