# Generated by Django 2.1 on 2020-02-02 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tetelek', '0002_auto_20200202_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='tetelek',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('1'), related_name='tetelek_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tetelek',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=models.SET('1'), related_name='tetelek_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
