# Generated by Django 3.0.2 on 2020-02-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tetelek', '0003_tetelek_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tetelek',
            name='photo',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
