# Generated by Django 2.1 on 2020-02-02 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tetelek', '0003_auto_20200202_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tetelek',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artists.Artist'),
        ),
        migrations.AlterField(
            model_name='tetelek',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('1'), related_name='created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tetelek',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=models.SET('1'), related_name='modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
