# Generated by Django 3.0.2 on 2020-01-05 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0002_auto_20200105_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=None)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('artist', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artists.Artist')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
