# Generated by Django 3.0.2 on 2020-01-05 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technics', '0003_auto_20200101_1314'),
        ('items', '0005_item_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tech',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='technics.Technic'),
        ),
    ]
