# Generated by Django 3.0.2 on 2020-01-05 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_auto_20200105_1124'),
        ('technics', '0003_auto_20200101_1314'),
        ('items', '0009_auto_20200105_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='artist',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='artists.Artist'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tech',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='technics.Technic'),
        ),
    ]
