# Generated by Django 3.0.1 on 2020-01-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technics', '0002_technic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technic',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
