# Generated by Django 3.0.1 on 2019-12-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'vezeteknev'},
        ),
    ]
