# Generated by Django 3.0.1 on 2019-12-29 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20191228_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'Ügyfelek'},
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[0-9a-zA-ZáéíóőűöüúÁÉÍÓŐŰÚ]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
