# Generated by Django 3.0.1 on 2020-01-05 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appraisers',
            options={'ordering': ['name'], 'verbose_name_plural': 'Becsüsők'},
        ),
    ]
