# Generated by Django 3.0.1 on 2020-01-07 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisers', '0002_auto_20200105_1108'),
        ('appraisers', '0002_auto_20200101_1908'),
    ]

    operations = [
    ]
