# Generated by Django 3.0.2 on 2020-01-06 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0002_auto_20200105_1124'),
        ('technics', '0003_auto_20200101_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=None)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('artist', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='artists.Artist')),
                ('tech', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='technics.Technic')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
