# Generated by Django 3.0.2 on 2020-01-09 07:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ajax', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ajax',
            managers=[
                ('next', django.db.models.manager.Manager()),
            ],
        ),
    ]
