# Generated by Django 3.0.2 on 2020-01-09 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajax', '0002_auto_20200109_0855'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ajax',
            managers=[
            ],
        ),
    ]
